baseURL = "http://benrutter.github.io"
languageCode = "en-us"
title = "Hi, I'm Ben 🛸"
theme = "bluey"

pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/benrutter"

[[params.social]]
name = "Mastodon"
icon = "twitter"
url = "https://graphics.social/@houseofleft"

[[params.social]]
name = "Mastodon"
icon = "linkedin"
url = "https://linkedin.com/in/benrrutter"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/posts/index.xml"
