baseURL = "http://benrutter.github.io"
languageCode = "en-uk"
title = "Hi, I'm Ben 🛸"
theme = "hugo-bearblog"

pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[[menu.main]]
name = "Code"
url = "https://github.com/benrutter"
weight = 2

[[menu.main]]
name = "Art"
url = "https://graphics.social/@houseofleft"
weight = 3

[[menu.main]]
name = "RSS"
url = "/posts/index.xml"
weight = 4
